project: 
  type: website

title: "UU Programming Cafe" # change me
theme: code-cafe.scss

website: 
  navbar: 
    logo: assets/img/uu-winter.png
    right: 
      - href: about.qmd
      - href: meetups/index.qmd
      - icon: github
        aria-label: Link to programming-cafe GitHub
        href: https://github.com/UtrechtUniversity/uu-programming-cafe